# Generated by Django 5.1.7 on 2025-04-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='temperature',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
