version: "3.9"

services:
  backend:
    build: .
    container_name: django_app
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8080:8000"
    depends_on:
      - db
    env_file:
      - postgres.env

  db:
    image: postgres:alpine
    env_file:
      - api.env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/code/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  static_volume:
